### ISSUE TITLE
get start esp8266 mesh

### ISSUE THREAD

**Issue by miladshoaei** [PhracturedBlue/ESP8266MQTTMesh#11]
Make sure you have the latest version of ESP8266MQTTMesh before reporting an issue.

### Please Provide the following information:
- ESP8266MQTTMesh version:
- AsyncMQTTClient version:
- ESPAsyncTCP version:
- ESP8266 Core version:

**Are you using platformio or Arduino?**

**Description of problem:**

**Comment by miladshoaei** [comment]
Hello friends
Excuse me that my English language is bad. I want to implement Mesh Networks with esp8266, what should I study to get started?
Thanks

**Comment by PhracturedBlue** [comment]
take a look at examples/ESP8266MeshHelloWorld
it should show how to use the Mesh.

**Comment by miladshoaei** [comment]
@PhracturedBlue 
Thanks
Is it necessary to install the firmware?

**Comment by miladshoaei** [comment]
Thanks
Is it necessary to install the firmware?

**Comment by PhracturedBlue** [comment]
Assuming you are still interested.  Each node in the mesh must have a firmware based on the ESP82666MQTTMesh code.  The nodes don't all need the same firmeware though.  Each node must be initially connected to the MQTT broker to register it, after which time, it can be put in service to connect to other mesh nodes as needed
