### ISSUE TITLE
How to use it on Arduino IDE?

### ISSUE THREAD

**Issue by tanker11** [PhracturedBlue/ESP8266MQTTMesh#12]
Make sure you have the latest version of ESP8266MQTTMesh before reporting an issue.

- ESP8266MQTTMesh version: 0.8.4
- AsyncMQTTClient version: 0.8.1
- ESPAsyncTCP version: 1.1.0
- Arduino IDE: 1.8.4

**Description of problem:**
On Arduino IDE I could not install the library correctly as installing from ZIP resulted in "file does not contain a valid library".
Is there a manual way to do that?

**Comment by sahilparekh** [comment]
Hi, Quickest way would be:
1) Create a folder "ESP8266MQTTMesh" in Arduino/Library
2) Copy "Base64.h", "Base64.cpp", "ESP8266MQTTMesh.h", "ESP8266MQTTMesh.cpp" & "ESP8266MQTTMeshBuilder.h"
3) Restart Arduino then try to include the library. (All Header files will be included but only keep "ESP8266MQTTMesh.h")
