### ISSUE TITLE
Compile Issues

### ISSUE THREAD

**Issue by hevnsnt** [PhracturedBlue/ESP8266MQTTMesh#15]
Make sure you have the latest version of ESP8266MQTTMesh before reporting an issue.

### Please Provide the following information:
- ESP8266MQTTMesh version: v0.8.4
- AsyncMQTTClient version: v1.1.1
- ESPAsyncTCP version: v1.1.1
- ESP8266 Core version: v1.0

**If you are you using platformio or Arduino, which one?**
platformio

**Description of problem:**
Getting compile issues:

```
Compiling .pioenvs/nossl/src/ESP8266MeshHelloWorld.ino.o
/Users/xxxxx/repos/ESP8266MQTTMesh/examples/ESP8266MeshHelloWorld/src/ESP8266MeshHelloWorld.ino:30:25: error: 'OUT_TOPIC' was not declared in this scope
const char *out_topic = OUT_TOPIC;
^
/Users/xxxxx/repos/ESP8266MQTTMesh/examples/ESP8266MeshHelloWorld/src/ESP8266MeshHelloWorld.ino:31:24: error: 'IN_TOPIC' was not declared in this scope
const char *in_topic = IN_TOPIC;
^
```

**Comment by PhracturedBlue** [comment]
I have updated the HelloWorld example to be easier to configure.  It should be available in 0.8.5 within 24hours, or fetch the latest version from github
