### ISSUE TITLE
Real Work Scenario, How is the MQTT Broker?

### ISSUE THREAD

**Issue by filzek** [PhracturedBlue/ESP8266MQTTMesh#16]
Hi,

My issue is previous from the current usage, but is very nice to understand prior to go live.

In this scenario:

MQTT Broker Sever is: https://www.cloudmqtt.com
Router is:  192.168.1.254
Chanel is: 1
SSID is:  trythisrouter
PASSWD: is:  routerisfine

There will be 10 ESP8266 to test.
4 are Wemos Mini D1 with 2 relay in each
6 are Wemos D1 R2 with 3 relays in each

Our scenario is to deploy those ESP all around to test the MESH and have all log/debug enable to trace.

Please advise how the ESP8266 could be setup with ESP8266MQTTMesh

Thanks

**Comment by PhracturedBlue** [comment]
you must install the firmware onto each node (use the HellowWorld example to start).
You should start with a local broker.  I have not done any testing with DNS, and do not guarantee it will work.  You should specify the IP address of your broker, and ensure security is not enabled.

Each node must be initially started in range of the wifi network so it can register with the broker.  After that, the nodes can be spread out, but each node must be in range of at least one other node or to the router.

After you have verified the connectivity using a local broker, you can attempt to see if DNS works and file tickets if need be.
