### ISSUE TITLE
Gateway_ID not working

### ISSUE THREAD

**Issue by keatontaylor** [PhracturedBlue/ESP8266MQTTMesh#36]
Make sure you have the latest version of ESP8266MQTTMesh before reporting an issue.

Latest version of all

**Description of problem:**

When attempting to define GATEWAY_ID in the example hello world mesh project. It doesn't seem to work such to force the nodes to avoid connecting to wifi that do not match that ID. 

```
#ifndef GATEWAY_ID
  #define GATEWAY_ID 146743
#endif
```

**Comment by PhracturedBlue** [comment]
GATEWAY_ID must be specified in the platformio.ini file, and cannot go into the example c++ code.

**Comment by keatontaylor** [comment]
Thank you, got it solved.
