### ISSUE TITLE
WDT reset on wifi connect

### ISSUE THREAD

**Issue by C-monC** [PhracturedBlue/ESP8266MQTTMesh#41]
- ESP8266MQTTMesh version: 1.0.2
- ESP8266 12-E
- On platformio
- In Helloworld example

When the setup up finishes and the esp8266 matches the SSID the hardware wdt reset is activated. I have implemented ESP.wdtDisable() (in setup) to give it more time to connect but still get the same problem.

Serial monitor output: https://pastebin.com/TxpqwVqJ

I have tried multiple AP's and double checked the login credentials but get the same error for all.

**Comment by PhracturedBlue** [comment]
Does this happen with 1.0.2?  1.0.0 was never meant to be released, and it was quite broken.

**Comment by C-monC** [comment]
Sorry, I meant 1.0.2( just re-downloaded files to be sure). I noticed even with the AP off the esp still returns 
```[match_networks] Comparing pi``` and if I boot the pi nothing changes. 

I have also tried with my home network as the AP and my pc as the MQTT broker

**Comment by PhracturedBlue** [comment]
I assume you are using the helloworld example?  please post your credentials.h

**Comment by C-monC** [comment]
Yes, I'm using the helloworld example

credentials.h: https://pastebin.com/xF29kZGU

**Comment by PhracturedBlue** [comment]
Your network list needs to have a null element at the end

**Comment by C-monC** [comment]
Thank you for your help. That was the problem

**Comment by PhracturedBlue** [comment]
I should probably use a more C++ way of defining those so you don't need the null element like a std::vector, or maybe even just add it into the builder.  I'll think about it
