### ISSUE TITLE
Subscribe to topic.

### ISSUE THREAD

**Issue by austonpramodh** [PhracturedBlue/ESP8266MQTTMesh#43]
I am using the latest version of ESP8266MQTTMesh Library and arduino for uploading the code.

How do I subscribe to a topic and use call back function? Please Help

please give an example of callback and subscribe topic if possible.

**Comment by PhracturedBlue** [comment]
You can't subscribe to an arbitrary topic.  The default topic that is subscribed to is 'esp8266-in/' though this can be changed during initialization with the setTopic() build helper.
The specified callback will be called whenever a topic of 'esp8266-in/<nodeid>/' is received (or if 'esp8266-in/broadcast' is received)

<nodeid> is the node's chipid in hex (not zero padded)..  ie if your chipid was 123456 the expected topic would be 'esp8266-in/1e240/'

**Comment by austonpramodh** [comment]
Thanks, man... I check everything and it worked... Thank You.

**Comment by austonpramodh** [comment]
Hey, Is there any way to remove the prefix of subscribing and publish? or at least remove the chipID leaving only ESP8266-out? so that I can inform broker that this device is connected.

**Comment by PhracturedBlue** [comment]
Each node will leave a retained message on the broker notifying that it is available.
The only way that nodes are addressable is either by the chipid or via 'broadcast'.  Nodes can send retain messages through the publish API, but they will always contain the chipid

**Comment by austonpramodh** [comment]
Hey, M sorry I forgot to thank you. And I figured out how to change the
topics. thank you so much...

**Comment by austonpramodh** [comment]
Hey,

I just signed the petition "IT Minister Shri Ravishankar Prasad: 90 days of
Notice period in IT and ITes is harming industry and needs to be 30 days."
and wanted to see if you could help by adding your name.

Our goal is to reach 7,500 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/X7zNsGY6SZ

Thanks!
Auston

**Comment by austonpramodh** [comment]
Hi there,
Please ignore the last email you received from "austonpramodh@gmail.com".
It was a mistake. My sincere apologies.

Thank you,
-- 

Regards,
Auston Pramodh Barboza
www.auston.dev
