### ISSUE TITLE
Transferring Byte type of data

### ISSUE THREAD

**Issue by eporocrail** [PhracturedBlue/ESP8266MQTTMesh#65]
I am able to transfer data of byte data type after conversion into string type, but when I receive those data I have to manipulate the data to convert back to byte type.
The problem is that the system I am exchanging data with only accepts data of byte data type.
Is there a way to transfer with your system data of byte type?

Regards
eporocrail

**Comment by simone1999** [comment]
hello, as far as i know the MQTT Messages themself doesn't have such thing as a Datatype, because yo send a Stream of Bytes and the receiver interprets this Stream like he wants.
