### ISSUE TITLE
ESP32 connecting to SSID issue

### ISSUE THREAD

**Issue by eporocrail** [PhracturedBlue/ESP8266MQTTMesh#74]
After compilation and loading the software into the ESP32 module, the program gets stuck trying to connect to the right SSID. The ESP8266 version of the same program is connecting without any problem.

Any suggestion?

**Comment by simone1999** [comment]
hey,
you coud provide us with the output from your ESP32, maybe that is going to help us find the Issue.

**Comment by eporocrail** [comment]
Just the message that the module is connecting to the SSID.

But in the meanwhile the reason to switch from 8266 to 32 has gone.
Thanks so far.

**Comment by Tim97Egl** [comment]
I have the same issue. Has anyone figured out a solution?
