### ISSUE TITLE
Automatic build feature

### ISSUE THREAD

**Issue by kazimyuksel** [PhracturedBlue/ESP8266MQTTMesh#77]
It is not an issue but a question and a possible request.

As far as i understand, at the startup, esp8266 builds the mesh and connects to available mesh nodes.

But what happens if user turns off a node? Does network automatically adapts or just fails?

Reason i am asking is that in my setup each IoT device in home is a node. LED Bulb is a node, but i can turn off the light switch, in that case node turns off. Does mesh network automatically adapts to new case, or just fails?

If it does not build itself again, is there a possible way to do it?
Thank you

**Comment by PhracturedBlue** [comment]
nodes should dynamically reconfigure as they enter and leave the mesh
